# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 2, 12, 2, 20, 43, 679359, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
